### ISSUE TITLE
Ошибка при копировании настроек

### ISSUE THREAD

**Issue by asamats** [itdoginfo/ansible-openwrt-hirkn#1]
Получаю следующие ошибки:
`fatal: [192.168.1.1]: FAILED! => {"changed": true, "checksum": "638f04858d5887b50c61b7c9a41ad8a068ce7385", "dest": "/etc/hotplug.d/iface/30-rknroute", "md5sum": "db11dee959eb32d01d34b35c24195d21", "msg": "chmod (/etc/hotplug.d/iface/30-rknroute) failed: chmod: invalid mode 'False'", "src": "/root/.ansible/tmp/ansible-tmp-1550921521.83-94202376827463/source"}`
`fatal: [192.168.1.1]: FAILED! => {"changed": true, "checksum": "ffe1b15697030e4be45349840923a773806c9cbc", "dest": "/etc/config/dnscrypt-proxy", "md5sum": "d833f620cf01f61e2c5697f61f14df6c", "msg": "chmod (/etc/config/dnscrypt-proxy) failed: chmod: invalid mode 'False'", "src": "/root/.ansible/tmp/ansible-tmp-1550922152.67-233527556261273/source"}`

Ошибка возникает, как я понял, из-за того, что template файлы не с теми правами и владельцами. не стал разбираться. Файлы копируются, я просто на время закомментировал эти строки.

P.S. Спасибо за то, что поделились своим трудом.

**Comment by itdoginfo** [comment]
Похоже на баг в старых версиях Ansible, какую версию используете?
У меня 2.5.1

**Comment by asamats** [comment]
У меня ansible 2.7.7
Да я весь день мучаюсь, не могу настроить wireguard. Почему-то коннект с сервером не проходит. при это пакеты отправляет, но ничего не получает.

Понимаю что, что-то не так делаю. Но что, не могу понять.

**Comment by asamats** [comment]
Проблема исчезла, после того как указал имя, группа и права на файлы, копируемые на роутер.

**Comment by itdoginfo** [comment]
Действительно, в 2.7 параметр mode для template обязателен. Добавил

Насчет wireguard, проверьте настройки: ключи, порты, адреса. Проверьте что у сервера открыт порт.
Бывает необходимо сделать down\up
```
wg-quick down wg0 && wg-quick up wg0
```
Для получения деталей о статусе wg используйте
```
wg show
```
