### ISSUE TITLE
Отстутствует пакет dnsmasq-full

### ISSUE THREAD

**Issue by Classes123** [itdoginfo/ansible-openwrt-hirkn#5]
В dev-репозитории (для mipsel_24kc в моем случае) отсутствует пакет dnsmasq-full. Также его нет по [ссылке](https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/dnsmasq-full_2.89-1_mipsel_24kc.ipk) из примера.

**Comment by itdoginfo** [comment]
Да, на данный момент его там нет. Что-то у них сломалось. Скинул в тг канал этот пакет https://t.me/itdoginf/16
