### ISSUE TITLE
потерял слеши

### ISSUE THREAD

**Issue by DimiDr0l** [itdoginfo/ansible-openwrt-hirkn#7]
https://github.com/itdoginfo/ansible-openwrt-hirkn/blob/da9a4c731b36f336885064bae593d504238646de/getdomains-install.sh#L220

**Comment by itdoginfo** [comment]
Где именно? Это файл, а не директория

**Comment by DimiDr0l** [comment]
cp /etc/config/dhcp /etc/config/dhcp-old
